services:
  - type: web
    name: smart-preprocessing-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    rootDir: "Smart Data Preprocessing AI"